name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'

    - name: Build
      run: cd richardlennox && hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        emptyCommits: false
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: richard-lennox/richard-lennox.github.io
        publish_branch: master
        publish_dir: ./richardlennox/public
        cname: blog.richardlennox.com
        commitMessage: ${{ github.event.head_commit.message }}